id: I8F1332E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:04:23+00:00'
last_modified: '2022-06-08T09:33:59.361918+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105858
  title: ཨ་མདོའི་ལ་གཞས་རྨ་ཀླུང་སྒེག་མོའི་རླབས་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F33:
      image_group_id: I1PD105860
      title: ''
      total_pages: 528
      order: 1
      base_file: 4F33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
