id: P006910
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:12.696899
source_metadata:
  id: bdr:W1PD105858
  title: ཨ་མདོའི་ལ་གཞས་རྨ་ཀླུང་སྒེག་མོའི་རླབས་སྒྲ།
  author: ''
  volumes:
    102fca614cfe44fca16533498e87e987:
      image_group_id: I1PD105860
      title: ''
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
